Feature 8 offline media
Metatavu/oss-surveys-customer pull request #10
Opened 2023-04-06 18:59 UTC by villejuutila

Resolves #8

2023-04-14 10:27 UTC, EVP1989 approved these changes
Approved with comment

2023-04-14 10:27 UTC, EVP1989 commented on lib/files/offline_file_controller.dart
> +import 'dart:io';
```suggestion
import "dart:io";
```

2023-04-14 10:27 UTC, EVP1989 commented on lib/mqtt/listeners/surveys_listener.dart
> +    //   String externalId = _getSurveyIdFromMessage(message);
Remove this if its not in use

2023-04-14 14:02 UTC, lauriLukkarinen requested changes

2023-04-14 14:02 UTC, lauriLukkarinen commented on lib/mqtt/listeners/abstract_listener.dart
> +    "$baseTopic/delete":handleDelete
```suggestion
    "$baseTopic/create": handleCreate,
    "$baseTopic/update": handleUpdate,
    "$baseTopic/delete": handleDelete
```

2023-04-14 14:02 UTC, lauriLukkarinen commented on lib/mqtt/mqtt_client.dart
> +      if (listeners.containsKey(c[0].topic)) {
Maybe 'messages' instead of 'c'?

2023-04-14 14:46 UTC, villejuutila commented on lib/files/offline_file_controller.dart
> +import 'dart:io';
Resolved

2023-04-14 14:46 UTC, villejuutila commented on lib/mqtt/listeners/surveys_listener.dart
> +    //   String externalId = _getSurveyIdFromMessage(message);
Resolved

2023-04-14 14:47 UTC, villejuutila commented on lib/mqtt/listeners/abstract_listener.dart
> +    "$baseTopic/delete":handleDelete
Resolved

2023-04-14 14:47 UTC, villejuutila commented on lib/mqtt/mqtt_client.dart
> +      if (listeners.containsKey(c[0].topic)) {
Resolved

2023-04-17 11:49 UTC, lauriLukkarinen approved these changes

2023-04-18 05:35 UTC, merged